### ISSUE TITLE
Will it be possible to extend to Linux & MacOS also?

### ISSUE THREAD

**Issue by massisenergy** [trinitronx/vncpasswd.py#18]
Thanks very much for this useful package. I tested in macOS Catalina, it yielded some errors like 

`
❯  python2 ./vncpasswd.py -e 12345678 -f obfuscatedPassFile
Cannot read from Windows Registry on a Darwin system
Cannot write to Windows Registry on a Darwin system
Encrypted Bin Pass= '��1d���s'
Encrypted Hex Pass= 'f0e43164f6c2e373'
`

However, it wrote the password in the file and I could use it for my automated VNC Server authentication through the command line. Since I am not familiar with python, I request to make the script more generalised to be useful for more people, if possible...

**Comment by trinitronx** [comment]
Yeah, this is just a warning printed on non-Windows systems.  Originally, I developed this project on Windows and then got it working on Linux, & macOS later.  Now my old Windows laptop died (battery charging circuit on motherboard broken). So I have no way of testing this on Windows anymore... thus I just left alone all the code handling Windows & registry stuff so it wouldn't break.

These are just print statements, and they're safe to ignore.

The code handles them like this:

```
$ ag 'Cannot write'  -B10 
vncpasswd.py
155-            print 'Length: %d' % len(args.passwd)
156-            print 'Hex Length: %d' % len(hexpasswd)
157-        crypted = do_crypt(args.passwd, args.decrypt)
158-
159-    if ( args.filename != None and not args.decrypt ):
160-        do_file_out(args.filename, crypted, args.hex)
161-    if ( args.registry and not args.decrypt and platform.system().startswith('Windows')):
162-        reg = get_realvnc_key()
163-        reg.setval('Password', crypted, wreg.WindowsRegistry.REG_BINARY)
164-    elif not platform.system().startswith('Windows'):
165:        print 'Cannot write to Windows Registry on a %s system' % platform.system()


$ ag 'Cannot read'  -B10 
vncpasswd.py
121-    args = parser.parse_args()
122-    if (args.test):
123-        run_tests()
124-
125-    if ( args.filename == None and args.passwd == None and (args.registry == False or not platform.system().startswith('Windows')) ):
126-        parser.error('Error: No password file or password passed\n')
127-    if ( args.registry and args.decrypt and platform.system().startswith('Windows')):
128-        reg = get_realvnc_key()
129-        ( args.passwd, key_type) = reg.getval("Password")
130-    elif not platform.system().startswith('Windows'):
131:        print 'Cannot read from Windows Registry on a %s system' % platform.system()
```

**Comment by trinitronx** [comment]
I can probably just change the `elif` case tests to check for `args.registry` also:

Like this perhaps:

```
elif args.registry and not platform.system().startswith('Windows'):
```
