### ISSUE TITLE
d3des.py

### ISSUE THREAD

**Issue by sk3lk0** [trinitronx/vncpasswd.py#6]
C:\Users\bot>py "E:\Новая папка (5)\Новая папка\LaZagne-master\LaZagne-master\Windows\laZagne.py"
Traceback (most recent call last):
  File "E:\Новая папка (5)\Новая папка\LaZagne-master\LaZagne-master\Windows\laZagne.py", line 19, in <module>
    from lazagne.config.manage_modules import get_categories
  File "E:\Новая папка (5)\Новая папка\LaZagne-master\LaZagne-master\Windows\lazagne\config\manage_m
odules.py", line 45, in <module>
    from lazagne.softwares.sysadmin.vnc import Vnc
  File "E:\Новая папка (5)\Новая папка\LaZagne-master\LaZagne-master\Windows\lazagne\softwares\sysad
min\vnc.py", line 3, in <module>
    import d3des as d
  File "C:\Users\bot\AppData\Local\Programs\Python\Python37-32\d3des.py", line 48
    bytebit = [ 01, 02, 04, 010, 020, 040, 0100, 0200 ] # VNC version
\\\\\\\\\\\\\\\\\\\\\\\\\\^
SyntaxError: invalid token
can you help me with fix?

**Comment by trinitronx** [comment]
@sk3lk0 : Hmm... looks like you're running on Windows set with Cyrillic localized file paths?  Not sure if that could be the cause, but maybe check your Python version?

Try running the Python REPL and testing that line of code works to set variable `bytebit`?

```
C:\Path\to\your\python.exe
>>> bytebit = [ 01, 02, 04, 010, 020, 040, 0100, 0200 ]
>>> print bytebit
[1, 2, 4, 8, 16, 32, 64, 128]
```

This code supports Python `2.7.x` versions.  Make sure your version of Python is compatible?

**Comment by sk3lk0** [comment]
im using 3.7 python

**Comment by trinitronx** [comment]
@sk3lk0 : Ok, that's definitely why... this code is written for Python 2 and would need to be converted to support Python 3.  There was a [PR made][1] for locking the "[shebang line][2]" to Python2... however there wasn't a known easy & reliable method for this cross-platform.

I'm not sure how Windows would even deal with this other than probably ignore it anyway and just use the program specified for the `.py` file type association to run it.

Your best bet is to find a way to install Python 2 alongside Python 3 on Windows, and then use Python 2 for this script.  Or, you could try to translate the code to work with Python 3.  There are some unit tests in this project so they could be of some help to check that it still works after translation.

[1]: https://github.com/trinitronx/vncpasswd.py/pull/3
[2]: https://en.wikipedia.org/wiki/Shebang_(Unix)
